; PHP production tuned for Laravel
upload_max_filesize = 20M
post_max_size = 20M
memory_limit = 256M
max_execution_time = 120
max_input_vars = 5000

; Opcache
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.revalidate_freq=0
opcache.validate_timestamps=0
opcache.enable_cli=0

; Logging
log_errors=On
error_log=/proc/self/fd/2

; Date
date.timezone=UTC

; Session
session.gc_probability=1

; Expose off for security
expose_php=Off
